[[configs]]
source_url = "https://hac.oispahalla.com/api/stats"
# Check for new data every minute
fetch_interval_s = 30
try_parse_json = true

[[configs]]
source_url = "https://analytics.oispahalla.com/api/stats"
# Check for new data every minute
fetch_interval_s = 60
try_parse_json = true

[[configs]]
source_url = "https://lb.oispahalla.com/scores/size/4/stats"
# Check for new data every 24 hours
fetch_interval_s = 86400
try_parse_json = true

[[configs]]
source_url = "https://lb.oispahalla.com/scores/size/3/stats"
# Check for new data every 24 hours
fetch_interval_s = 86400
try_parse_json = true
